### ISSUE TITLE
Input of the non-difference questions.

### ISSUE THREAD

**Issue by Kingofolk** [Holipori/EKAID#1]
Hi! Thanks for your great work. Could you please tell me when facing the non-difference questions, _e.g., where is the abnormality_, what are put into the network? Or in other words, did we still need to input both the main and reference images to answer the non-difference questions? Thank you very much.
Best

**Comment by Holipori** [comment]
Hi, thank you for your interest in our work! Yes, the input to the model always includes both main and reference images, even for non-difference questions. The model will assign the weights internally and focus on the main image only when answering non-difference questions.

**Comment by Kingofolk** [comment]
Thank you very much. Wish you have a nice day!
