### ISSUE TITLE
evaluation metrics problem

### ISSUE THREAD

**Issue by big-white-rabbit** [Holipori/EKAID#10]
Hello! In the paper, I noticed the best accuracy results on non-"Difference" questions of the MIMIC-Diff-VQA dataset. May I ask if there are results for other evaluation metrics, such as F1 score? Or accuracy results on whole MIMIC-Diff-VQA dataset. 
Thank you!

**Comment by Holipori** [comment]
Hello!

Thank you for your interest in our paper. We currently do not have other evaluation metrics, but we will include them in the updated version of the paper. The accuracy and F1 score will not be added to the whole MIMIC-Diff-VQA dataset, as the "difference" questions have far too many answer candidates. Using these classification-based metrics is not very meaningful in this context. 
Thank you!
