### ISSUE TITLE
Problem of "test-mimic. py" ,Index Error

### ISSUE THREAD

**Issue by ZuoZicheng** [Holipori/EKAID#11]
Hi, thank you very much for sharing the code. When I was reproducing your work, I was able to run "train_mimic. py" to generate the "checkpoint best. pt" file normally, but encountered an exception while running "test_mimic. py". The error is: "IndexError: Index (377089) out of range for (0-377087)". The specific content is as follows:
![indexerror](https://github.com/Holipori/EKAID/assets/73999174/bfa74d8e-be63-4935-ac2a-1b6bdba32445)

The code indicates that two files need to be called, among which "self.features4[ ]" calls the "cmd_bbox_di_feats.hdf5" file. The range of the "image_features" attribute in this file is (377088, 52, 1024), and "self.feature_idx" needs to call the "VQA-mimic_dataset.h5" file. The "feature_idx" attribute value in this file has a value greater than 377088, which causes this exception.

What is the reason for the mismatch between the two file ranges?

**Comment by Holipori** [comment]
Hi, thank you for your interest in our work.
This is strange. The size for the "cmd_bbox_di_feats.hdf5" file should be 377110, the same size as the MIMIC-CXR dataset. 
Could you please check the size of the "mimic_shape_full.pkl" file? It should be 377110 as well. If it's not 377110, it may need to be regenerated using converter.py, then rerun the feature generation code.

**Comment by ZuoZicheng** [comment]
Thank you for your prompt reply.

I checked file "mimic_shape_full.pkl" and as expected, its size is indeed 307088.

But when I run program “converter.py”, the size of the "mimic_shape_full.pkl" file I get is still 307088.

Can you provide download links for the converted PNG files, "mimic_shape_full.pkl" files, "mimic_shapeid_full.pkl", and “dicom2id.pkl” files?

**Comment by ZuoZicheng** [comment]
Thank you for your prompt reply.

I checked file "mimic_shape_full.pkl" and as expected, its size is indeed 377088.

But when I run program “converter.py”, the size of the "mimic_shape_full.pkl" file I get is still 377088.

Can you provide download links  for the converted PNG files, "mimic_shape_full.pkl" files, "mimic_shapeid_full.pkl", and “dicom2id.pkl” files to my email: 107556523224@stu.xju.edu.cn?

**Comment by Holipori** [comment]
Hi, 

Sure, I just sent you the files to your email.
But if the size of the "mimic_shape_full.pkl" file you got is still 377088, it suggests that the MIMIC-CXR-JPG dataset you downloaded could be incomplete. I would recommend double-checking and using my files as references to find the missing data, or you may still encounter errors in the later parts of the code.
