### ISSUE TITLE
keyerror in dataset_preparetion.py

### ISSUE THREAD

**Issue by jfffgit** [Holipori/EKAID#12]
when just using a part of pictures in database to generate a new dataset,the dataset_preparetion.py file cannot create ./data/VQA_mimic_dataset.h5 completely.
![Uploading 1715230671750.png…]()

**Comment by jfffgit** [comment]
![1715230671750](https://github.com/Holipori/EKAID/assets/169330898/03ee214f-dae1-4412-9e08-85d64b1c742f)

**Comment by Holipori** [comment]
Hi,

I'm sorry for the late reply. I have been really busy with work and personal matters recently.

Yes, this error is normal if you use a part of the pictures. You need to remove all the question-answer pairs that are not related to your prepared pictures. An easy way to fix this is to add a "try-except" on line 191.
