### ISSUE TITLE
Dose abnormality-type questions with "yes/no" answer belong to close-ended question?

### ISSUE THREAD

**Issue by Kingofolk** [Holipori/EKAID#14]
Hi Xinyue!
When computing the accuracy of non-difference questions (the attached table), dose the abnormality-type questions with "yes/no" answer belong to close-ended question?
The reason why I ask is that some abnormality-type questions have the answers which detaily describes the present abnormalities, but some others only replies 'yes/no'. Thanks a lot!

![image](https://github.com/Holipori/EKAID/assets/37804732/a092309c-95e0-4415-a31f-c1a36977684e)

best regards
Kingofolk

**Comment by Holipori** [comment]
Yes, they are! All the questions with yes/no answers are considered closed-ended questions.

I'm sorry for the late reply. I have been busy with my summer internship recently.

**Comment by Kingofolk** [comment]
Get. Thanks a lot. Wish you a good experience in summer internship!
