### ISSUE TITLE
datasets publication time

### ISSUE THREAD

**Issue by afasijbfk** [Holipori/EKAID#3]
hi, 
After reading your paper, I am extremely interested in your dataset and would like to follow in your footsteps for further research in the field. So can you please tell me if the dataset will be made public? If it will, roughly when will it be made public？
Thank you very much. Sincerely hope that your research will go further.
best regards.

**Comment by Holipori** [comment]
Hi, Thank you very much for being interested in our work. Yes! the dataset will be made public. It's currently still under review on Physionet. Last week, we received feedback from the review, made the necessary revisions, and resubmitted it. Hopefully, we will be able to make it public soon. Thank you for your patience!
