### ISSUE TITLE
Problems with the value of entropy_loss

### ISSUE THREAD

**Issue by afasijbfk** [Holipori/EKAID#6]
hi,
During running train_mimic.py, I found that the value of entropy_loss is always -0.0, and the other values of loss are changing normally. So I would like to ask if the value of entropy_loss also stays -0.0 or change?
thank you very much!

**Comment by afasijbfk** [comment]
hi,
may I ask what is the size of the cmb_bbox_di_feats.hdf5 file obtained after running combine_dicts.py in the feature extraction module? It is saved in . /model/.data file.
Best regards.

**Comment by Holipori** [comment]
Hi, 
Yes, the entropy_loss is an extra loss that is not in use. I have removed it from the updated code. Thanks for bringing it to our attention.

The extracted cmb_bbox_di_feats.hdf5 file is 141164391864 bytes.

**Comment by afasijbfk** [comment]
hi, 
When training, I noticed that the BLUE evaluation metrics would suddenly drop at the 14kth Step, what could be the reason for this phenomenon? And I have trained two rounds and it happens in both of them.
![image](https://github.com/Holipori/EKAID/assets/102459451/73c1690a-624a-424a-8f03-54e94ac62302)
![image](https://github.com/Holipori/EKAID/assets/102459451/873963e6-5d6b-42c7-9852-c077c05da603)

**Comment by Holipori** [comment]
Hi,

Could you try different learning rates and random seeds? for example, Could you try lr= 5e-5, seed=1250 or 1238?
![image](https://github.com/Holipori/EKAID/assets/43333502/19ad9a75-1e87-4be9-8cdf-7e9ec6efe858)

**Comment by afasijbfk** [comment]
Thanks again to you, I'll try it later and then share my results.
best regards.
