### ISSUE TITLE
How did you create the study2dicom.pkl

### ISSUE THREAD

**Issue by dongzizhu** [Holipori/EKAID#7]
Hi author,

Could you please explain how you created the study2dicom.pkl file? I understand there are usually 2 images for each study, how did you choose which image to use as the study image and reference image?

Thanks in advance!

**Comment by Holipori** [comment]
Hi,

The study2dicom.pkl file was obtained from the original MIMIC-CXR-JPG metafile (mimic-cxr-2.0.0-metadata), to identify the correspondence relationship between study_id and dicom_id. For studies with multiple CXR scans, we chose the AP or PA view.

As for the selection of the study image and reference image, each pair of images is from different visits (studies) of the same patient. For each pair of studies, we choose the previous visit as the “reference” visit and the future visit as the “main” (current) visit.

**Comment by dongzizhu** [comment]
Got it. Thx!
