### ISSUE TITLE
Problem with the answers to difference questions.

### ISSUE THREAD

**Issue by dongzizhu** [Holipori/EKAID#9]
Hi,

I just noticed a weird thing about the answers to some of the difference questions.

In the comparison of missing and additional abnormalities, some of the answers include a combination of _pneumonia_ and other abnormalities. Like

_the main image has additional findings of lung opacity, and pneumonia atelectasis, granuloma, and pneumonia than the reference image_

Is _pneumonia atelectasis_ a different thing from pneumonia and atelectasis? It's not mentioned in the abnormality type of questions and I couldn't find a similar reference elsewhere.

Thanks in advance!

**Comment by Holipori** [comment]
Hi,

No, pneumonia and atelectasis are two different conditions. This seems to be a mistake. Thank you for pointing it out. 

In the code, we equate "infection" with "pneumonia" (which is true in most cases, as suggested by radiologists). So, we transform "infection" into "pneumonia" in the code. In some rare cases, the code might keep both "pneumonia" that was transformed from "infection" and the "pneumonia" that was directly extracted from the report. We have updated the code for generating the dataset.

You can fix this problem by globally replacing "and pneumonia atelectasis" with "atelectasis." By counting, there are 53 such cases in the dataset. Considering the size of the dataset, their impact on the training process should be limited. But, we will still release a new version of the dataset on PhysioNet.

Thank you!
